spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/moayoeats
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER_NAME}
    password: ${PASSWORD}
#    data:
#      mongodb:
#        uri: mongodb+srv://${MONGO_USER_NAME}:${MONGO_PASSWORD}@${CLUSTER_URL}/?retryWrites=true&w=majority

  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  thymeleaf:
    cache: false
    suffix: .html
#    prefix: src/main/resources/templates/

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

  # application.properties
logging:
  level:
    root: debug